// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeLU-O9KSfWMoZsxw0kWa4XZ-pR8OO5DI',
    appId: '1:626109551689:web:7647588bfd037b9b9d9b98',
    messagingSenderId: '626109551689',
    projectId: 'arrti-cf128',
    authDomain: 'arrti-cf128.firebaseapp.com',
    storageBucket: 'arrti-cf128.appspot.com',
    measurementId: 'G-2JJBTTL2NN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVBl0T42M8QreH9ng3-CC4U1Gsq8m-j4w',
    appId: '1:626109551689:android:15911bbae115949c9d9b98',
    messagingSenderId: '626109551689',
    projectId: 'arrti-cf128',
    storageBucket: 'arrti-cf128.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY5mS7UmnrOVrJIB1aK0x1sfDDu5k3iOQ',
    appId: '1:626109551689:ios:b28e685af402fb1d9d9b98',
    messagingSenderId: '626109551689',
    projectId: 'arrti-cf128',
    storageBucket: 'arrti-cf128.appspot.com',
    androidClientId: '626109551689-lhtmo72ugjtg1iec3lf3843eb1o25ppf.apps.googleusercontent.com',
    iosClientId: '626109551689-1ijicuvb93g0c3hhfg2rog0dubpc7odp.apps.googleusercontent.com',
    iosBundleId: 'com.AZainapps.apniMandiAdmin',
  );
}
